# Generated by Django 4.0.3 on 2022-03-17 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catagery',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sub_catagery',
            new_name='sub_category',
        ),
    ]
