# Generated by Django 4.0.3 on 2022-03-21 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_item_json_orders_items_json_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='items_json',
            new_name='item_json',
        ),
    ]
